version: '3.7'
services:
  front_dev:
    container_name: front_dev
    build:
      context: .
      dockerfile: Dockerfile
      target: front_dev
    tty: true
    ports:
      - 8080:8080
    volumes:
      - .:/app
      - node_modules:/app/client/node_modules
    working_dir: /app/client

volumes:
  node_modules: {}
