version: '3.7'
services:
  front_dev:
    container_name: front_dev
    build:
      context: .
      dockerfile: Dockerfile
      target: front_dev
    tty: true
    ports:
      - 8080:8080
      - 6006:6006
    volumes:
      - .:/app
      - node_modules:/app/client/node_modules
    working_dir: /app/client

  server_dev:
    container_name: server_dev
    build:
      context: .
      dockerfile: Dockerfile
      target: server_dev
    tty: true
    ports:
      - 8888:8888
    volumes:
      - .:/app
    working_dir: /app/server

volumes:
  node_modules: {}
